name: "Quake"
version: "1.0"
author: "RoztoczaNaDensflorze"
main: "com.quake.QuakeMain"
api-version: "1.16"
commands:
  quake-start:
    description: starts a quake game

  quake-join:
    description: joins player to lobby for a game of quake

  quake-prestart:
    description: pre game settings for quake

  quake-leave:
    description: leaves game of quake

  jump:
    description: jumps

  resp:
    description: test

  multiverse:
    description: teleports player to diffrent world